# Generated by Django 4.1.7 on 2023-03-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('followers', models.TextField(blank=True)),
                ('followings', models.TextField(blank=True)),
            ],
        ),
    ]
