# Generated by Django 4.1.7 on 2023-03-30 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0008_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
